export const MODULE_CODES = {
  // Risk
  RISK: "RISK",
  RISK_OVERVIEW: "RISK_OVERVIEW",
  RISK_REGISTERS: "RISK_REGISTERS",
  RISK_HEATMAP: "RISK_HEATMAP",
  KRI_DASHBOARD: "KRI_DASHBOARD",
  RISK_ACTIONS: "RISK_ACTIONS",
  RISK_INCIDENTS: "RISK_INCIDENTS",
  RISK_ACCEPTANCES: "RISK_ACCEPTANCES",

  // Audit
  AUDIT: "AUDIT",
  AUDIT_OVERVIEW: "AUDIT_OVERVIEW",
  AUDIT_TASKS: "AUDIT_TASKS",
  AUDIT_PLANS: "AUDIT_PLANS",
  AUDIT_WPS: "AUDIT_WPS",
  AUDIT_REPORTS: "AUDIT_REPORTS",

  // Core config
  CONFIGS: "CONFIGS",
  BRANCH_MGMT: "BRANCH_MGMT",
  DEPT_MGMT: "DEPT_MGMT",
  WORKFLOW_CONFIG: "WORKFLOW_CONFIG",
  USER_MGMT: "USER_MGMT",

  // Module settings
  MODULE_SETTINGS: "MODULE_SETTINGS",
  AUDIT_MODULE_CONFIG: "AUDIT_MODULE_CONFIG",
  RISK_MODULE_CONFIGS: "RISK_MODULE_CONFIGS"
} as const;

export type ModuleCode = (typeof MODULE_CODES)[keyof typeof MODULE_CODES];
